const thrownItems: string[] = [
	'cheese',
	'tomatoes',
	'a black hole',
	'chicken nuggets',
	'anthrax',
	'deez nuts',
	'deez nuts',
	'deez nuts',
	'deez nuts',
	'a party',
	'a chair',
	'bad weather',
	'a tornado',
	'a hockey puck',
	'a knuckle sandwitch',
	'a toaster',
	'a penny',
	'a horse',
	'dogs',
	'ones and zeroes',
	'smelly cheese',
	'an angry beaver',
	'a cobra chicken',
	'a keyboard',
	'water on',
	'a brick',
	'mosquitoes',
	'a D20',
	'a flaming brick',
	'a nuke',
	'air pods',
	'a knife',
	'money',
	'a nebula',
	'dirt',
	'sand',
	'a snowball',
	'an ice bucket',
	'fire',
	'hot coffee',
	'cold coffee',
	'a 1cm socket',
	'a 10mm socket',
	'a 0.1dm socket',
	'a 0.01m socket',
	'a toaster',
	'a train',
	'a gummy bear',
	'a polar bear',
	'a grizzly bear',
	'an angry monkey',
	'a snickers',
	'a sharknado',
	'a heatwave',
	'snow',
	'a snowball',
	'pocket sand',
	'a ketchup bottle',
	'an onion',
	'a rotten apple',
	'the Catholic Church',
	'mormons',
	'the book',
	'a fork',
	'mosquitoes',
	'wasps',
	'punches',
	'sticks and stones',
	'a problem',
	'a solution',
	'a complement',
	'a complement',
	'a complement',
	'positivity',
	'a good day',
	'a chocolate factory',
	'a golden ticket',
	'monsters',
	'a snake',
	'the force',
	'a Redbull',
	'the CN Tower',
	'a train',
	'a road runner',
	'a wascally wabbit',
	'a cookie',
	'cake',
	'a crack addiction',
	'toothpicks',
	'bad code',
	'computer errors',
	'a rotary phone',
	'a sonic screwdriver',
	'IRL ads',
	'a warrant for arrest',
	'dirty underwear',
	'sweaty gym socks',
	'Karen',
	'an HOA violation',
	'Mjolnir',
	'one of Yzma\'s potions',
	'a flower pot',
	'a newt',
	'an email from HR',
	'a naked mole rat',
	'Mexican Black Tar Heroin',
	'nothing',
	'a temper tantrum',
	'a cup of tea',
	'the USS Enterprise',
	'the USS Enterprise-D',
	'a space shuttle',
	'the Millenium Falcon',
	'everything',
	'hot sauce',
	'a hot dog',
	'a hot pocket',
	'a hot potato',
	'a hot mess',
	'spicy food',
	'pepper spray',
	'death, by snu snu',
	'death, by snu snu',
	'death, by snu snu',
	'Lego bricks',
	'a Nokia 3310',
	'a hot take',
	'a bone',
	'an ATV',
	'beans',
	'bug spray',
	'a hornet\'s nest',
	'the sound of a sassy husky',
	'nothing but the truth',
	'a shoe',
	'an iPhone',
	'a dodgeball',
	'a baseball',
	'a football',
	'a soccer ball',
	'a basketball',
	'a hockey puck',
	'a hockey stick',
	'Wayne Gretzky',
	'deez nuts',
	'deez nuts',
	'a kick in the butt',
	'zombies',
	'a zombie apocalypse',
	'Nazi zombies',
	'Nazis',
	'an old Italian woman who thinks you need more food',
	'a 3D printer',
	'poutine',
	'Quebec construction',
	'a Nanaimo bar',
	'a Timbit',
	'a Timbit',
	'a Timbit',
	'a Timbit',
	'an Xbox controller',
	'a PS5 controller',
	'a PS4 controller',
	'a PS3 controller',
	'a PS2 controller',
	'a PS1 controller',
	'a dead racoon',
	'fake news',
	'Taylor Swift concert tickets',
	'the remote',
	'a nuke',
	'a nuke',
	'a nuke',
	'a nuke',
	'an orphanage',
	'an orphan',
	'your Amazon package',
];

export default thrownItems;
